/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JRootPane;


/**
 *
 * @author HaiHoang
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public static int ms;
    private JFrame frame = new JFrame();
    public MainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    public MainJFrame(int n) {
        initComponents();
        this.setLocationRelativeTo(null);
        String name = new DAO().getStaff(n);
        hi.setText("Xin chào "+name+" !");
        ms = n;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTrangChu = new javax.swing.JButton();
        btnSach = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        lblTrangChu = new javax.swing.JLabel();
        lblSach = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblDocGia = new javax.swing.JLabel();
        lblMuonTra = new javax.swing.JLabel();
        hi = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SÁCH");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 102)));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Đăng xuất !");

        btnTrangChu.setBackground(new java.awt.Color(204, 204, 255));
        btnTrangChu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.setBorder(null);
        btnTrangChu.setContentAreaFilled(false);
        btnTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnSach.setBackground(new java.awt.Color(204, 204, 255));
        btnSach.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSach.setText("SÁCH");
        btnSach.setBorder(null);
        btnSach.setContentAreaFilled(false);
        btnSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(204, 204, 255));
        btnNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorder(null);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnDocGia.setBackground(new java.awt.Color(204, 204, 255));
        btnDocGia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDocGia.setText("ĐỘC GIẢ");
        btnDocGia.setBorder(null);
        btnDocGia.setContentAreaFilled(false);
        btnDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });

        btnMuonTra.setBackground(new java.awt.Color(204, 204, 255));
        btnMuonTra.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnMuonTra.setText("MƯỢN TRẢ");
        btnMuonTra.setBorder(null);
        btnMuonTra.setContentAreaFilled(false);
        btnMuonTra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonTraActionPerformed(evt);
            }
        });

        lblTrangChu.setBackground(new java.awt.Color(0, 204, 106));
        lblTrangChu.setForeground(new java.awt.Color(102, 255, 102));
        lblTrangChu.setOpaque(true);

        lblSach.setBackground(new java.awt.Color(204, 204, 255));
        lblSach.setForeground(new java.awt.Color(102, 255, 102));
        lblSach.setOpaque(true);

        lblNhanVien.setBackground(new java.awt.Color(204, 204, 255));
        lblNhanVien.setForeground(new java.awt.Color(102, 255, 102));
        lblNhanVien.setOpaque(true);

        lblDocGia.setBackground(new java.awt.Color(204, 204, 255));
        lblDocGia.setForeground(new java.awt.Color(102, 255, 102));
        lblDocGia.setOpaque(true);

        lblMuonTra.setBackground(new java.awt.Color(204, 204, 255));
        lblMuonTra.setForeground(new java.awt.Color(102, 255, 102));
        lblMuonTra.setOpaque(true);

        hi.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        hi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSach, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btnMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTrangChu)
                                    .addComponent(btnSach)
                                    .addComponent(btnNhanVien)
                                    .addComponent(btnDocGia)
                                    .addComponent(btnMuonTra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                                    .addComponent(lblSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                                    .addComponent(lblNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                                    .addComponent(lblDocGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                                    .addComponent(lblMuonTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(820, 550));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        lblTrangChu.setBackground(new Color(0,204,106));
        lblSach.setBackground(new Color(204,204,255));
        lblNhanVien.setBackground(new Color(204,204,255));
        lblDocGia.setBackground(new Color(204,204,255));
        lblMuonTra.setBackground(new Color(204,204,255));
        jDesktopPane1.removeAll();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachActionPerformed
        lblTrangChu.setBackground(new Color(204,204,255));
        lblSach.setBackground(new Color(0,204,106));
        lblNhanVien.setBackground(new Color(204,204,255));
        lblDocGia.setBackground(new Color(204,204,255));
        lblMuonTra.setBackground(new Color(204,204,255));
        jDesktopPane1.removeAll();
        ListBook lb = new ListBook();
        jDesktopPane1.add(lb);
        lb.setVisible(true);
    }//GEN-LAST:event_btnSachActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        lblTrangChu.setBackground(new Color(204,204,255));
        lblSach.setBackground(new Color(204,204,255));
        lblNhanVien.setBackground(new Color(0,204,106));
        lblDocGia.setBackground(new Color(204,204,255));
        lblMuonTra.setBackground(new Color(204,204,255));
        jDesktopPane1.removeAll();
        ListStaff lb = new ListStaff();
        lb.setVisible(true);
        jDesktopPane1.add(lb);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        lblTrangChu.setBackground(new Color(204,204,255));
        lblSach.setBackground(new Color(204,204,255));
        lblNhanVien.setBackground(new Color(204,204,255));
        lblDocGia.setBackground(new Color(0,204,106));
        lblMuonTra.setBackground(new Color(204,204,255));
        jDesktopPane1.removeAll();
        ListUser lb = new ListUser();
        lb.setVisible(true);
        jDesktopPane1.add(lb);
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonTraActionPerformed
        lblTrangChu.setBackground(new Color(204,204,255));
        lblSach.setBackground(new Color(204,204,255));
        lblNhanVien.setBackground(new Color(204,204,255));
        lblDocGia.setBackground(new Color(204,204,255));
        lblMuonTra.setBackground(new Color(0,204,106));
    }//GEN-LAST:event_btnMuonTraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new MainJFrame().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel hi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDocGia;
    private javax.swing.JLabel lblMuonTra;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSach;
    private javax.swing.JLabel lblTrangChu;
    // End of variables declaration//GEN-END:variables
}
